/**
 * pdfGenerator.js — Generate downloadable PDF bill using jsPDF
 */

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function generateBillPDF(bill, company) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const template = company?.template_name || "Modern";

  if (template === "Professional") {
    renderProfessionalTemplate(doc, bill, company);
  } else {
    renderModernTemplate(doc, bill, company);
  }

  doc.save(`Invoice_${company?.name?.replace(/\s+/g, "_")}_${bill.employee_name?.replace(/\s+/g, "_")}.pdf`);
}

function renderModernTemplate(doc, bill, company) {
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = 30;

  // ── Top Left: Logo / Invoice Title ──
  if (company?.logo_url) {
    try { doc.addImage(company.logo_url, "PNG", margin, 18, 14, 14); } catch(e) {}
  }
  doc.setFont("helvetica", "bold");
  doc.setFontSize(26);
  doc.setTextColor(30, 41, 59);
  doc.text("INVOICE", margin + (company?.logo_url ? 18 : 0), 28);

  // ── Top Right: Company Info ──
  doc.setFontSize(10);
  doc.setTextColor(51, 65, 85);
  doc.text(company?.name?.toUpperCase() || "COMPANY NAME", pageW - margin, 24, { align: "right" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(100, 116, 139);
  doc.text(company?.address || "Address Line 1, City, State", pageW - margin, 29, { align: "right" });
  doc.text(`${company?.phone || "Phone Number"} | GST: ${company?.gst_number || "N/A"}`, pageW - margin, 34, { align: "right" });

  // ── Divider ──
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(margin, 42, pageW - margin, 42);

  // ── Billing Details ──
  y = 55;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  doc.setTextColor(100, 116, 139);
  doc.text("BILLED TO", margin, y);
  doc.text("DETAILS", pageW - margin - 45, y);

  y += 6;
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text(bill.employee_name || "Employee Name", margin, y);
  
  doc.setFontSize(9);
  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "normal");
  doc.text(`Invoice Number:`, pageW - margin - 45, y);
  doc.setFont("helvetica", "bold");
  doc.text(`INV-${bill.id || "001"}`, pageW - margin, y, { align: "right" });

  y += 5;
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  doc.setFont("helvetica", "normal");
  doc.text(bill.designation || "Designation", margin, y);
  doc.text(`Billing Date:`, pageW - margin - 45, y);
  doc.text(`${bill.bill_date || "Date"}`, pageW - margin, y, { align: "right" });

  y += 5;
  doc.text(`PAN: ${bill.pan_number || "N/A"}`, margin, y);
  doc.text(`Due Date:`, pageW - margin - 45, y);
  doc.text(`${bill.bill_date || "Date"}`, pageW - margin, y, { align: "right" });

  // ── Table ──
  y += 18;
  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    head: [["DESCRIPTION", "RATE (PER DAY)", "QUANTITY (DAYS)", "AMOUNT"]],
    body: [
      ["Professional Salary Fees", `₹ ${((bill.monthly_salary || 0) / (bill.working_days || 30)).toFixed(2)}`, `${bill.present_days || 0}`, `₹ ${(bill.monthly_salary || 0).toFixed(2)}`],
      ["Deductions (Absents / LWP)", `₹ ${((bill.monthly_salary || 0) / (bill.working_days || 30)).toFixed(2)}`, `(${bill.absent_days || 0})`, `- ₹ ${(bill.deduction || 0).toFixed(2)}`],
    ],
    styles: { fontSize: 8.5, cellPadding: 5, textColor: [30, 41, 59], font: "helvetica" },
    headStyles: { fillColor: [248, 250, 252], textColor: [71, 85, 105], fontStyle: "bold", cellPadding: 6 },
    theme: "striped",
  });

  // ── Summary ──
  y = doc.lastAutoTable.finalY + 12;
  const summaryX = pageW - margin - 65;
  
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.setFont("helvetica", "normal");
  doc.text("Subtotal", summaryX, y);
  doc.text(`₹ ${(bill.monthly_salary || 0).toFixed(2)}`, pageW - margin, y, { align: "right" });

  y += 6;
  doc.text(`Deductions (${bill.absent_days || 0} days)`, summaryX, y);
  doc.text(`- ₹ ${(bill.deduction || 0).toFixed(2)}`, pageW - margin, y, { align: "right" });

  y += 8;
  doc.setDrawColor(226, 232, 240);
  doc.line(summaryX, y - 4, pageW - margin, y - 4);
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(79, 70, 229); // Modern indigo
  doc.text("Total Amount", summaryX, y + 2);
  doc.text(`₹ ${(bill.net_amount || 0).toFixed(2)}`, pageW - margin, y + 2, { align: "right" });

  // ── Footer ──
  const footerY = doc.internal.pageSize.getHeight() - 15;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.setFont("helvetica", "normal");
  doc.text("Formal record generated by BillFlow AI Assistant.", margin, footerY);
}

function renderProfessionalTemplate(doc, bill, company) {
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 20;

  // ── Borders ──
  doc.setDrawColor(200, 200, 200);
  doc.rect(5, 5, pageW - 10, doc.internal.pageSize.getHeight() - 10);

  // ── Header ──
  doc.setFont("times", "bold");
  doc.setFontSize(24);
  doc.setTextColor(30, 30, 30);
  doc.text(company?.name || "OFFICIAL INVOICE", margin, 25);

  doc.setFontSize(10);
  doc.setFont("times", "normal");
  doc.text(company?.address || "Business Location", margin, 35);
  doc.text(`GSTIN: ${company?.gst_number || "N/A"}`, margin, 40);

  doc.setLineWidth(0.5);
  doc.line(margin, 45, pageW - margin, 45);

  // ── Bill Info ──
  doc.setFontSize(10);
  doc.text(`Invoice Number: BS-${bill.id}`, pageW - margin, 25, { align: "right" });
  doc.text(`Billing Date: ${bill.bill_date}`, pageW - margin, 31, { align: "right" });

  // ── Tables ──
  autoTable(doc, {
    startY: 55,
    margin: { left: margin, right: margin },
    head: [["Service Description", "Unit Price", "Quantity", "Total"]],
    body: [
      [`Monthly Salary for ${bill.employee_name}`, `₹ ${bill.monthly_salary}`, "1 Month", `₹ ${bill.monthly_salary}`],
      ["Less: Unpaid Absents", `₹ ${(bill.monthly_salary / bill.working_days).toFixed(2)}`, `${bill.absent_days} Days`, `-₹ ${bill.deduction}`],
    ],
    headStyles: { fillColor: [60, 60, 60] },
    theme: "grid"
  });

  const finalY = doc.lastAutoTable.finalY + 10;
  doc.setFont("times", "bold");
  doc.text(`Net Amount Payable: ₹ ${bill.net_amount}`, pageW - margin, finalY, { align: "right" });

  doc.setFont("times", "normal");
  doc.text("Authorized Signature", pageW - margin - 40, finalY + 30);
  doc.line(pageW - margin - 50, finalY + 25, pageW - margin, finalY + 25);

  doc.setFontSize(8);
  doc.text("This document is a formal record of payment and serves as a valid tax invoice.", pageW / 2, doc.internal.pageSize.getHeight() - 15, { align: "center" });
}
