/**
 * pdfGenerator.js — Generate downloadable PDF bill using jsPDF
 */

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function generateBillPDF(bill, company) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const template = company?.template_name || "Modern";

  if (template === "Professional") {
    renderProfessionalTemplate(doc, bill, company);
  } else {
    renderModernTemplate(doc, bill, company);
  }

  doc.save(`Invoice_${company?.name?.replace(/\s+/g, "_")}_${bill.employee_name?.replace(/\s+/g, "_")}.pdf`);
}

function renderModernTemplate(doc, bill, company) {
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 20;

  // ── Header ──
  doc.setFillColor(17, 19, 24);
  doc.rect(0, 0, pageW, 55, "F");

  // Logo
  if (company?.logo_url) {
    try { doc.addImage(company.logo_url, "PNG", margin, 12, 12, 12); } catch(e) {}
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(79, 142, 247);
  doc.text(company?.name?.toUpperCase() || "COMPANY NAME", margin + (company?.logo_url ? 16 : 0), 22);

  doc.setFontSize(8);
  doc.setTextColor(140, 146, 170);
  doc.setFont("helvetica", "normal");
  doc.text(company?.address || "Company Address", margin, 32);
  doc.text(`GST: ${company?.gst_number || "N/A"} | PH: ${company?.phone || "N/A"}`, margin, 37);

  doc.setFontSize(9);
  doc.setTextColor(200, 210, 230);
  doc.text(`Invoice #${bill.id || "N/A"}`, pageW - margin, 18, { align: "right" });
  doc.text(`Date: ${bill.bill_date}`, pageW - margin, 25, { align: "right" });
  doc.text(`Emp ID: ${bill.employee_id}`, pageW - margin, 32, { align: "right" });

  // ── Content ──
  let y = 68;
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(40, 45, 60);
  doc.text("EMPLOYEE DETAILS", margin, y);
  
  y += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(80, 85, 100);
  doc.text(`${bill.employee_name} (${bill.designation})`, margin, y);
  doc.text(`Email: ${bill.email}`, margin, y + 5);

  y += 15;
  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    head: [["Description", "Details", "Amount (₹)"]],
    body: [
      ["Basic Salary", `${bill.working_days} Days`, `₹ ${bill.monthly_salary?.toFixed(2)}`],
      ["Attendance", `${bill.present_days} Present / ${bill.absent_days} Absent`, ""],
      ["Deduction", `Per Day: ₹${(bill.monthly_salary / bill.working_days).toFixed(2)}`, `- ₹ ${bill.deduction?.toFixed(2)}`],
    ],
    styles: { fontSize: 9, cellPadding: 4 },
    headStyles: { fillColor: [17, 19, 24], textColor: [255, 255, 255] },
    theme: "striped"
  });

  y = doc.lastAutoTable.finalY + 10;
  doc.setFillColor(79, 142, 247);
  doc.rect(pageW - margin - 60, y, 60, 12, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.text("TOTAL PAYABLE", pageW - margin - 56, y + 7.5);
  doc.text(`₹ ${bill.net_amount?.toFixed(2)}`, pageW - margin - 4, y + 7.5, { align: "right" });

  const footerY = doc.internal.pageSize.getHeight() - 20;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Modern Template Generated by BillFlow AI.", margin, footerY);
}

function renderProfessionalTemplate(doc, bill, company) {
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 20;

  // ── Borders ──
  doc.setDrawColor(200, 200, 200);
  doc.rect(5, 5, pageW - 10, doc.internal.pageSize.getHeight() - 10);

  // ── Header ──
  doc.setFont("times", "bold");
  doc.setFontSize(24);
  doc.setTextColor(30, 30, 30);
  doc.text(company?.name || "OFFICIAL INVOICE", margin, 25);

  doc.setFontSize(10);
  doc.setFont("times", "normal");
  doc.text(company?.address || "Business Location", margin, 35);
  doc.text(`GSTIN: ${company?.gst_number || "N/A"}`, margin, 40);

  doc.setLineWidth(0.5);
  doc.line(margin, 45, pageW - margin, 45);

  // ── Bill Info ──
  doc.setFontSize(10);
  doc.text(`Invoice Number: BS-${bill.id}`, pageW - margin, 25, { align: "right" });
  doc.text(`Billing Date: ${bill.bill_date}`, pageW - margin, 31, { align: "right" });

  // ── Tables ──
  autoTable(doc, {
    startY: 55,
    margin: { left: margin, right: margin },
    head: [["Service Description", "Unit Price", "Quantity", "Total"]],
    body: [
      [`Monthly Salary for ${bill.employee_name}`, `₹ ${bill.monthly_salary}`, "1 Month", `₹ ${bill.monthly_salary}`],
      ["Less: Unpaid Absents", `₹ ${(bill.monthly_salary / bill.working_days).toFixed(2)}`, `${bill.absent_days} Days`, `-₹ ${bill.deduction}`],
    ],
    headStyles: { fillColor: [60, 60, 60] },
    theme: "grid"
  });

  const finalY = doc.lastAutoTable.finalY + 10;
  doc.setFont("times", "bold");
  doc.text(`Net Amount Payable: ₹ ${bill.net_amount}`, pageW - margin, finalY, { align: "right" });

  doc.setFont("times", "normal");
  doc.text("Authorized Signature", pageW - margin - 40, finalY + 30);
  doc.line(pageW - margin - 50, finalY + 25, pageW - margin, finalY + 25);

  doc.setFontSize(8);
  doc.text("This document is a formal record of payment and serves as a valid tax invoice.", pageW / 2, doc.internal.pageSize.getHeight() - 15, { align: "center" });
}
